### ISSUE TITLE
Kill process dont stop docker image

### ISSUE THREAD

**Issue by mcaligares** [mcaligares/express-typescript#28]
When I kill the process, the console throw the following error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 85, in main
  File "compose/cli/main.py", line 145, in exit_with_metrics
  File "logging/__init__.py", line 1463, in error
  File "logging/__init__.py", line 1575, in _log
  File "logging/__init__.py", line 1544, in makeRecord
  File "logging/__init__.py", line 323, in __init__
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException
[81595] Failed to execute script docker-compose
```

Expected result: When kill the process, the docker image should be shutdown

**Comment by mcaligares** [comment]
In order to resolve this issue we need execute the `docker-compose` command instead `npm run`
